# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metadata_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Metadata_tool(object):
    def setupUi(self, Metadata_tool):
        Metadata_tool.setObjectName("Metadata_tool")
        Metadata_tool.resize(313, 534)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Metadata_tool)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Metadata_tool)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.comboBox_metadata = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_metadata.setObjectName("comboBox_metadata")
        self.verticalLayout_7.addWidget(self.comboBox_metadata)
        self.stacked_metadata = QtWidgets.QStackedWidget(self.groupBox)
        self.stacked_metadata.setObjectName("stacked_metadata")
        self.page_view = QtWidgets.QWidget()
        self.page_view.setObjectName("page_view")
        self.verticalLayout_view = QtWidgets.QVBoxLayout(self.page_view)
        self.verticalLayout_view.setObjectName("verticalLayout_view")
        self.label_metadata = QtWidgets.QLabel(self.page_view)
        self.label_metadata.setWordWrap(True)
        self.label_metadata.setObjectName("label_metadata")
        self.verticalLayout_view.addWidget(self.label_metadata)
        self.stacked_metadata.addWidget(self.page_view)
        self.page_edit = QtWidgets.QWidget()
        self.page_edit.setObjectName("page_edit")
        self.verticalLayout_edit = QtWidgets.QVBoxLayout(self.page_edit)
        self.verticalLayout_edit.setObjectName("verticalLayout_edit")
        self.textEdit_metadata = QtWidgets.QTextEdit(self.page_edit)
        self.textEdit_metadata.setObjectName("textEdit_metadata")
        self.verticalLayout_edit.addWidget(self.textEdit_metadata)
        self.stacked_metadata.addWidget(self.page_edit)
        self.verticalLayout_7.addWidget(self.stacked_metadata)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_add = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 2, 0, 1, 1)
        self.checkBox_edit = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_edit.setObjectName("checkBox_edit")
        self.gridLayout.addWidget(self.checkBox_edit, 0, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 0, 2, 1, 1)
        self.pushButton_generateMeta = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_generateMeta.setObjectName("pushButton_generateMeta")
        self.gridLayout.addWidget(self.pushButton_generateMeta, 1, 0, 1, 1)
        self.pushButton_copyMetadata = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_copyMetadata.setObjectName("pushButton_copyMetadata")
        self.gridLayout.addWidget(self.pushButton_copyMetadata, 1, 2, 1, 1)
        self.pushButton_reset_one = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_reset_one.setObjectName("pushButton_reset_one")
        self.gridLayout.addWidget(self.pushButton_reset_one, 3, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 3, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 8)
        self.verticalLayout_7.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(Metadata_tool)
        self.stacked_metadata.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Metadata_tool)

    def retranslateUi(self, Metadata_tool):
        _translate = QtCore.QCoreApplication.translate
        Metadata_tool.setWindowTitle(_translate("Metadata_tool", "Metadata"))
        self.groupBox.setTitle(_translate("Metadata_tool", "Metadata"))
        self.label_metadata.setText(_translate("Metadata_tool", "Votre texte ici…"))
        self.pushButton_add.setText(_translate("Metadata_tool", "Add New Metadata"))
        self.checkBox_edit.setText(_translate("Metadata_tool", "Edit Metadata"))
        self.pushButton_save.setText(_translate("Metadata_tool", "Valid Changes"))
        self.pushButton_generateMeta.setText(_translate("Metadata_tool", "Generate Metadata"))
        self.pushButton_copyMetadata.setText(_translate("Metadata_tool", "Copy from cube"))
        self.pushButton_reset_one.setText(_translate("Metadata_tool", "Reset this metadata"))
        self.pushButton_cancel.setText(_translate("Metadata_tool", "Reset All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Metadata_tool = QtWidgets.QWidget()
    ui = Ui_Metadata_tool()
    ui.setupUi(Metadata_tool)
    Metadata_tool.show()
    sys.exit(app.exec_())
